### ISSUE TITLE
Odd UX when secure-proxy is in overflow menu

### ISSUE THREAD

**Issue by pdehaan** [mozilla-extensions/secure-proxy#346]
I spotted this while my browser was narrow and the toolbar icon went into the overflow menu. Note that the image doesn't stretch the entire width now, the buttons and text are no longer centered (because the panel seems wider), and we seem to have two title areas:

![Privacy_Protections_and_Secure_Proxy_-_Smartsheet_com_and_Firefox_67_0_4__See_All_New_Features__Updates_and_Fixes](https://user-images.githubusercontent.com/557895/62641757-2f36d180-b8f9-11e9-8025-b14022971a38.png)

vs regular toolbar UX:

![Privacy_Protections_and_Confirm_add-on_permissions_·_Issue__345_·_mozilla_secure-proxy](https://user-images.githubusercontent.com/557895/62641705-129a9980-b8f9-11e9-819d-671ae5038f80.png)

---

![Privacy_Protections](https://user-images.githubusercontent.com/557895/62641965-92286880-b8f9-11e9-8ca3-d3542c503929.png)

/cc @brassy-

**Comment by bakulf** [comment]
The new UI should fix this issue.
