### ISSUE TITLE
The toolbar icon is a bit too small to differentiate between on and off

### ISSUE THREAD

**Issue by pdehaan** [mozilla-extensions/secure-proxy#361]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565309259070500):

> **[Julien Vehent 5:07 PM]:** the icon is a bit too small to differentiate between on and off. I had left it on without noticing.

/cc @moz-jvehent

**Comment by bakulf** [comment]
v23 has a completely new UI. Closing this bug.
