### ISSUE TITLE
Add docs/TESTPLAN.md

### ISSUE THREAD

**Issue by pdehaan** [mozilla-extensions/secure-proxy#37]
We should add a docs/TESTPLAN.md document which outlines what we (QA) should test.
Here's a sample TESTPLAN.md file from the [**mozilla/jestr-pioneer-shield-study**](https://github.com/mozilla/jestr-pioneer-shield-study/blob/master/docs/TESTPLAN.md) shield study.

Also, we should make sure we have local installation and development instructions somewhere (see #36).

**Comment by bakulf** [comment]
This bug can be closed. We have integrated tests.
