### ISSUE TITLE
MacOS experiencing random system crashes while running the proxy [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla-extensions/secure-proxy#500]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566407292033400),

~~Not sure if Christopher is using v0.5 or the newer v0.6. I asked in Slack and will update here when I get an answer.~~ He's on v0.6.

**Christopher Arnold Today at 10:08 AM**
Is anyone on a MacOS experiencing random system crashes while running the proxy?

**Christopher Arnold  3 hours ago**
A common aspect of the crash reports is the string:  "AppleEmbeddedPCIeUpLinkMgmt" which leads me to believe that the proxy is somehow interfering with something that the OS considers critical to its own function.  If anyone else is seeing this string in crash reports, we may have to isolate this issue for Mac users prior to launch.

**Keith Willowhawk  2 hours ago**
I haven’t experienced any issues with system stability, what kind of dock do you use?  I use a USBC dock, do you have the issue undocked also?

**Christopher Arnold  1 hour ago**
Thanks Keith!  It's a HyperDrive Solo 7-in-1.  I'll try working without it for a week to see if that might contribute.  I appreciate the tip!

---

**Christopher Arnold  12 minutes ago**
I'm on 0.6 and awaiting the 0.7 version to fix the "refused connections" error.  Should I try 0.7 for a while without the HyperDrive doc (which Keith suspects might have been the actual cause) before we dig into log errors?

**Christopher Arnold  4 minutes ago**
Keeping in mind that I can't prove this is related to proxy here are the two crashes I saved from my experience since integrating Secure Proxy 0.6:  https://docs.google.com/document/d/1OZhy185PbInJhu7qfI-Of5Ulx8FnAI76LHDE-HLfSyA/edit?usp=sharing  &  https://docs.google.com/document/d/1WGGhzpMeJ9Wnd8oGqYZQrJo-xgPpqZsS7elmCTLTBGo/edit?usp=sharing

**Comment by bakulf** [comment]
This can be closed. No new reports about this crash.
