### ISSUE TITLE
Secure Proxy and FxA account verification Inbox

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla-extensions/secure-proxy#604]
From @vbudhram

I wanted to reach out and give you some directions on how to test Secure Proxy with the new FxA account verification process we are experimenting with (verification with a code instead of email link). If you haven't seen it already, here are some links to feature docs [1] and UX [2].

This feature is currently only available in our stage environment [3]. To get the new account experience, you would simply have to opt into it by appending query params to the login url.

```
    ?forceExperiment=signupCode&forceExperimentGroup=treatment
```

Once [4] is deployed to our stage environment, then all proxy users will automatically get opted in and you will no longer have to append query params. Until then, the above will work. Let me know if you have any questions, or run into any issues. Thanks!

Vijay

**Comment by bakulf** [comment]
Do we still need to do this? @vladikoff
