### ISSUE TITLE
Retrospective logging?

### ISSUE THREAD

**Issue by mayhemer** [mozilla-extensions/secure-proxy#637]
When a problem appears it may already be too late to figure out what preceded and caused it.  We don't want an unattended logging for privacy reasons, but we also need information to be able to fix problems.

It would be nice to collect the logs in the `log` function to a rotational buffer of some reasonable size and, on demand via a button in the UI, flush to the console for pasting to issue comments.

**Comment by bakulf** [comment]
#921
