### ISSUE TITLE
Add notification for scenatio where Auto start is ON

### ISSUE THREAD

**Issue by bsurd** [mozilla-extensions/secure-proxy#776]
#### Notes:
With the current implementation, there is a notification where if auto-start is set to OFF the "Pass expired. Firefox Private Network is off" is displayed.
![image](https://user-images.githubusercontent.com/17178945/68949081-f5138080-07c1-11ea-9abf-96aeb4c5fa87.png)

A notification that the next pass has started after the current one has finished is missing. 
![missing](https://user-images.githubusercontent.com/17178945/68949503-d2ce3280-07c2-11ea-95c9-840e121128ef.jpg)

We only have notifications for the 5-minute reminders of what's going to happen after the last 5 minutes.
![image](https://user-images.githubusercontent.com/17178945/68949137-14aaa900-07c2-11ea-9e85-6d672a11ba9c.png)
 
#### Affected Platforms:
- Windows 10 (64-bit)
- Mac 10.14.2
- Linux Ubuntu 19.04 (64-bit)

#### Affected versions:
- unsigned v16 build

#### Steps to reproduce
1. Start a pass.
2. Enable the "Auto-Start Passes" option from settings.
3. Wait for the pass to expire.

#### Expected result
- A notification is displayed informing the user that the next pass has started.

#### Actual result:
- No notification is displayed.

**Comment by bakulf** [comment]
v23 doesn't have passes. Let's close this bug.
