### ISSUE TITLE
Sync pass time for different installments of SP

### ISSUE THREAD

**Issue by bsurd** [mozilla-extensions/secure-proxy#783]
#### Affected Platforms:
- Windows 10 (64-bit)
- Mac 10.14.2
- Linux Ubuntu 19.04

#### Affected versions:
- unsigned v16 build

#### Steps to reproduce
1. Install SP on any machine and start a pass.
2. Install SP on a secondary machine.
3. Observe the UI.

#### Expected result
- The remaining pass time is shown on the second machine as well after login.

#### Actual result:
- The pass time is not displayed.

#### Notes:
- The remaining pass time is displayed after the user turns on SP.

**Comment by bakulf** [comment]
v23 doesn't have passes. Let's close this bug.
