### ISSUE TITLE
 “Device-limit” message is not triggered for Subscription Proxy

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-extensions/secure-proxy#914]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.179.3;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have a mailinator testing account with an active subscription for Secure Proxy extension;
- have a VPN set to point to a US region;

 #### Steps to reproduce:
1. Open a new profile and install the latest version of SP;
2. Install the SP management extension and set the FxA to point to Stage;
3. Sign in from SP using the account from prerequisites;
4. Load SP main page https://stage-browser.guardian.nonprod.cloudops.mozgcp.net/ and subscribe;
5. Click on the SP icon from the toolbar and turn on the extension.
6. Go to a new profile (with no VPN installed) and repeat steps: 1 and 2.
7. Click on the SP icon from the toolbar and try to turn on the extension.

#### Expected result:
- The extension is not turned on. A device-limit message is displayed.

#### Actual result:
- The extension is not turned on. The offline message is displayed.
- If a VPN is installed and the region is set to a US one, the SP is turning into an “active” state.

####Notes:
- tried with 4 new profiles, same account, and the results are the same.
![device-limit](https://user-images.githubusercontent.com/15685960/87555479-2e3c2180-c6be-11ea-9de3-c94485fecdd8.png)

**Comment by bakulf** [comment]
This should be fixed in my latest commit on the server. and it has been tested today by @ValentinaPC

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78.0.2 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/87775128-3fa43b80-c82e-11ea-940a-6d5c023cc313.png)
