### ISSUE TITLE
Firefox Private Network Beta browser extension is mentioned in the in installation survey, after installing the new Subscription Proxy

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-extensions/secure-proxy#915]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.179.4;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have a mailinator testing account with an active subscription for Secure Proxy extension;
- have a VPN set to point to a US region;

 #### Steps to reproduce:
1. Open a new profile and install and activate the latest version of SP;
2. Observe the content of the triggered survey; (https://qsurvey.mozilla.com/s3/fpn-fitness-checkup)

#### Expected result:
- The content mentions the new Subscription Proxy.

#### Actual result:
- The content mentions the Firefox Private Network Beta.

![image](https://user-images.githubusercontent.com/15685960/87667844-b6c8c980-c773-11ea-9d49-f9ad4188dd69.png)

**Comment by bakulf** [comment]
We have disabled this survey in v23. Let's close this bug.
