### ISSUE TITLE
Subscription Proxy download page has incorrect tab title 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-extensions/secure-proxy#925]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.181.0

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an active FxA account;

 #### Steps to reproduce:
1. Load https://stage.guardian.nonprod.cloudops.mozgcp.net/ page;
2. Click on the “Subscribe for $2.99/Month” button;
3. Finalize subscription and click on the “Continue to download” button;
4. Observe “Download” page tab title;

#### Expected result:
- Tab title is “Download | product_name...”.

#### Actual result:
- Tab title is page URL (https://stage.guardian.nonprod.cloudops.mozgcp.net/browser/download)

![image](https://user-images.githubusercontent.com/15685960/88544866-c1f8e080-d022-11ea-8266-9217badccb93.png)

**Comment by rlr** [comment]
Pull request: https://github.com/mozilla-services/guardian-website/pull/905

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78.0.2 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/88633093-37b18a80-d0bd-11ea-9c24-e0ed3cfe0fdb.png)
