### ISSUE TITLE
Can't load voterstatus.sos.ca.gov website with FPN/SP

### ISSUE THREAD

**Issue by cpeterso** [mozilla-extensions/secure-proxy#927]
# Steps to reproduce
1. Enable FPN/SP extension.
2. Try to load https://voterstatus.sos.ca.gov/ (the State of California's voter registration website).

# Expected result:
The page should load successfully.

# Actual result:
The page fails to load. Firefox reports an error: "Unable to connect. Firefox can’t establish a connection to the server at voterstatus.sos.ca.gov." I'm running Firefox 81 Nightly on macOS 10.15.6.

If you disable FPN/SP and reload the page, the page will load correctly.

**Comment by bakulf** [comment]
I'm not able to reproduce it. I suspect it's a kind of IP-based block. Do you mind to send the network log?
https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging

**Comment by cpeterso** [comment]
> I'm not able to reproduce it. I suspect it's a kind of IP-based block. Do you mind to send the network log?
> https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging

I emailed my HTTP log to @bakulf.

**Comment by bakulf** [comment]
In the log I see this:

```
HTTP/2 502
cf-warp-error: 1
content-type: text/plain; charset=utf-8
content-length: 3
date: Thu, 06 Aug 2020 02:06:18 GMT
X-Firefox-Spdy: h2
```

It seems a cloudflare issue. I asked @mayhemer to take a look too.

**Comment by cpeterso** [comment]
Closing issue because https://voterstatus.sos.ca.gov/ loads correctly for me now with FPN. I'm using Firefox 82 Nightly and FPN version 23.
