### ISSUE TITLE
Can't change debugging server to stage for the firefox private network extension

### ISSUE THREAD

**Issue by clouserw** [mozilla-extensions/secure-proxy#938]
Moved from https://github.com/mozilla/fxa/issues/6858 ; Filed by @madalincm

> **Description**
> 
> The QA team is blocked from testing how a new created subscription on stage environment works with the FPN Extension
> 
> The FPN extension, by default, points to the production server. We use a management extension to make the fpn extension point to the staging environment and to be able to use a subscription created in there.
> At this moment that management extension does not work any more for us and we do not have another way to make the FPN extension point to stage.
> 
> We need a solution for this issue or we will not be able to cover some scenarios when running our fxa train tests. I'm adding the blocker label as this is currently blocking the QA team.

**Comment by bakulf** [comment]
Yesterday I provided a new extension to fix this issue. We can close this bug.

**Comment by madalincm** [comment]
We confirm that the new extension works for us! Thanks @bakulf for all the help!
