### ISSUE TITLE
FPN can't connect: test.factor11.cloudflareclient.com has no DNS resolution

### ISSUE THREAD

**Issue by ftobin** [mozilla-extensions/secure-proxy#950]
The host used for CONNECTING_HTTP_REQUEST, test.factor11.cloudflareclient.com, does not have any DNS resolution for A records, preventing the addon from thinking it's connected.  This seems to have started a few days ago.

FPN version 24.

```
$ dig @1.1.1.1 test.factor11.cloudflareclient.com  

; <<>> DiG 9.16.15 <<>> @1.1.1.1 test.factor11.cloudflareclient.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37117
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;test.factor11.cloudflareclient.com. IN A

;; AUTHORITY SECTION:
cloudflareclient.com.   3297    IN      SOA     hugh.ns.cloudflare.com. dns.cloudflare.com. 2261613430 10000 2400 604800 3600

;; Query time: 11 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Nov 09 09:17:36 EST 2021
;; MSG SIZE  rcvd: 122
```

**Comment by ftobin** [comment]
Just to clarify, FPN keeps saying "You are offline. Check your network connection and try again." when I try to turn it on, and I can tell it's trying to resolve `test.factor11.cloudflareclient.com`.

**Comment by aplunk** [comment]
@bakulf the secure extension should only resolve test.factor11.cloudflareclient.com inside of the tunnel.

**Comment by ftobin** [comment]
Hrm, you're right about the resolution -- I can verify that the host resolves inside the tunnel successfully.  Something else is messing with FPN..it reports not connected but is connected.  Apparently there are some firewall issues going on recently and will be fixed in the next release: https://www.reddit.com/r/firefox/comments/qfut2p/comment/hknxru9/?utm_source=share&utm_medium=web2x&context=3
